LearnASPNetCore31/App.Web/Controllers/Api/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

using App.DataAccess;
using App.DataAccess.Model;
using App.Web.Services;
using App.Web.Cache;

using Newtonsoft.Json;

namespace App.Web.Controllers.Api
{
    // [ApiController()]
    [Route("api/[controller]")]
    public class AuthorController : ControllerBase
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;
        // private readonly IMemoryCache _memoryCache;
        private readonly IMemoryCacheManager _memoryCacheManager;
        private readonly IContentCacheManager _contentCacheManager;

        public AuthorController(ApplicationDbContext db, IAuthorService authorService, IMemoryCacheManager memoryCacheManager, IContentCacheManager contentCacheManager)
        {
            _db = db;
            _authorService = authorService;
            _memoryCacheManager = memoryCacheManager;
            _contentCacheManager = contentCacheManager;
        }

        [HttpGet("get-all-cache-memory")]
        public async Task<IActionResult> GetAllCache()
        {
            string cacheKey = "GetAllAuthors";
            List<Author> authors;

            if (!_memoryCacheManager.TryGetCache<List<Author>>(cacheKey, out authors))
            {
                Thread.Sleep(10 * 1000);

                authors = await _authorService.GetAll(_db);
                _memoryCacheManager.SetCache<List<Author>>(cacheKey, authors);
            }

            return Ok(new
            {
                status = "success",
                message = "Authors Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = authors
                }
            });
        }

        [HttpGet("get-all-cache-content")]
        public async Task<IActionResult> GetAllCacheContent()
        {
            string cacheFilename = "GetAllAuthors.json";
            string authorsJson;
            List<Author> authors;

            if (!_contentCacheManager.TryGetCacheAsText(cacheFilename, out authorsJson))
            {
                Thread.Sleep(10 * 1000);

                authors = await _authorService.GetAll(_db);
                authorsJson = JsonConvert.SerializeObject(authors);

                _contentCacheManager.SetCacheAsText(cacheFilename, authorsJson);
            }
            else
            {
                try
                {
                    authors = JsonConvert.DeserializeObject<List<Author>>(authorsJson);
                }
                catch (JsonReaderException)
                {
                    Thread.Sleep(10 * 1000);

                    authors = await _authorService.GetAll(_db);
                    authorsJson = JsonConvert.SerializeObject(authors);

                    _contentCacheManager.SetCacheAsText(cacheFilename, authorsJson);
                }
            }

            return Ok(new
            {
                status = "success",
                message = "Authors Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = authors
                }
            });
        }

        [HttpGet("")]
        public async Task<IActionResult> GetAll()
        {
            var authors = await _authorService.GetAll(_db);

            return Ok(new
            {
                status = "success",
                message = "Authors Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = authors
                }
            });
        }

        [HttpPost("")]
        public async Task<IActionResult> Create([FromBody] Author author)
        {
            if (!ModelState.IsValid) return BadRequest(new
            {
                status = "fail",
                message = "Author Validation Invalid.",
                response = new
                {
                    errors = ModelState,
                    data = new { }
                }
            });

            await _authorService.Create(_db, author);

            return CreatedAtAction(nameof(Get), new { id = author.Id }, new
            {
                status = "success",
                message = "Author Created.",
                response = new
                {
                    errors = new object[] { },
                    data = author
                }
            });
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Get(int id)
        {
            var author = await _authorService.GetById(_db, id);

            if (author == null) return NotFound(new
            {
                status = "fail",
                message = $"Author with id: {id} not found.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });

            return Ok(new
            {
                status = "success",
                message = $"Author Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = author
                }
            });
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] Author author)
        {
            Author existingAuthor = await _authorService.GetById(_db, id);

            if (existingAuthor == null) return NotFound(new
            {
                status = "fail",
                message = $"Author with id: {id} not found.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });

            if (!ModelState.IsValid) return BadRequest(new
            {
                status = "fail",
                message = "Author Validation Invalid.",
                response = new
                {
                    errors = ModelState,
                    data = new { }
                }
            });

            await _authorService.UpdateById(_db, id, author);

            return Ok(new
            {
                status = "success",
                message = "Author Updated Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = existingAuthor
                }
            });
        }


        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await _authorService.GetById(_db, id);

            if (author == null) return NotFound(new
            {
                status = "fail",
                message = $"Author with id: {id} not found.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });

            await _authorService.DeleteById(_db, id);

            return Ok(new
            {
                status = "success",
                message = $"Author Deleted Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });
        }
    }
}

LearnASPNetCore31/App.Web/Controllers/Web/AuthorController.cs
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using App.DataAccess;
using App.DataAccess.Model;

using App.Web.Services;

namespace App.Web.Controllers.Web
{
    [Route("web/[controller]")]
    public class AuthorController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public AuthorController(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        [Route("index")]
        [Route("")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var authors = await _authorService.GetAll(_db);

            ViewBag.Authors = authors;

            return View();
        }

        [Route("{id}/details")]
        [Route("{id}")]
        [HttpGet]
        public async Task<IActionResult> Show(int id)
        {
            var author = await _authorService.GetById(_db, id);

            ViewBag.Author = author;

            return View();
        }

        [Route("{id}/edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var author = await _authorService.GetById(_db, id);

            ViewBag.Author = author;

            return View();
        }

        [Route("{id}/edit")]
        [HttpPost]
        public async Task<IActionResult> Update(int id, Author author)
        {
            await _authorService.UpdateById(_db, id, author);

            return RedirectToAction("Show", new { id = id });
        }

        [Route("{id}/destroy")]
        [HttpPost]
        public async Task<IActionResult> Destroy(int id)
        {
            await _authorService.DeleteById(_db, id);

            return RedirectToAction("Index");
        }

        [Route("create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("create")]
        [HttpPost]
        public async Task<IActionResult> Create(Author author)
        {
            await _authorService.Create(_db, author);

            return RedirectToAction("Index");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Create.cshtml.cs
using App.DataAccess;
using App.DataAccess.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public CreateModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        [BindProperty]
        public AuthorEntity Author { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();

            await _authorService.Create(_db, Author);

            return Redirect($"/Author/Show?id={Author.Id}");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Edit.cshtml.cs
using App.DataAccess;
using App.DataAccess.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public EditModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        [BindProperty]
        public AuthorEntity Author { get; set; }
        public int AuthorId { get; set; }

        /*
            id: AuthorId
        */
        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null) return Unauthorized();

            Author = await _authorService.GetById(_db, id);

            if (Author == null) return NotFound();

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();

            if (Author == null) return Unauthorized();

            AuthorEntity ExistingAuthor = await _authorService.GetById(_db, Author.Id);

            if (ExistingAuthor == null) return NotFound();

            await _authorService.UpdateById(_db, Author.Id, Author);

            return Redirect($"/Author/Show?id={Author.Id}");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Index.cshtml.cs
using System.Collections.Generic;
using App.DataAccess;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public IndexModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        public List<AuthorEntity> Authors { get; set; }

        public async Task OnGet()
        {
            Authors = await _authorService.GetAll(_db);
        }

        /*
            id: AuthorId
        */
        public async Task<IActionResult> OnPostDelete(int id)
        {
            AuthorEntity existingAuthor = await _authorService.GetById(_db, id);
            if (existingAuthor == null) return NotFound();

            await _authorService.DeleteById(_db, id);

            return Redirect("/Author");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Show.cshtml.cs
using System.Collections.Generic;
using App.DataAccess;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class ShowModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public ShowModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        public AuthorEntity Author { get; set; }
        public int AuthorId { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return Unauthorized();
            }

            AuthorId = (int)id;

            Author = await _authorService.GetById(_db, AuthorId);

            if (Author == null) return NotFound();

            return Page();
        }

        /*
            id: AuthorId
        */
        public async Task<IActionResult> OnPostDelete(int id)
        {
            AuthorEntity existingAuthor = await _authorService.GetById(_db, id);
            if (existingAuthor == null) return NotFound();

            await _authorService.DeleteById(_db, id);

            return Redirect("/Author");
        }
    }
}

LearnASPNetCore31/App.Web/Views/Author/Create.cshtml
@using App.DataAccess.Model
@model Author
@{
    Layout = "_Page";

    ViewData["Title"] = "Author Create Page";
    ViewData["Subtitle"] = $"This is an Author of Creating Page";
}

<div class="container">
    <div class="row">
        <div class="col">
            <form asp-controller="Author" asp-action="Create" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input type="text" asp-for="Name" class="form-control" placeholder="Author Name"
                        aria-describedby="Author Name">
                    <small class="text-muted">Please input an Author Name</small>
                </div>
                <div class="form-group d-flex">
                    <a class="btn btn-primary text-white mr-2" asp-controller="Author" asp-action="Index">Author
                        List</a>
                    <button type="submit" class="btn btn-success text-white mr-2">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

LearnASPNetCore31/App.Web/Views/Author/Edit.cshtml
@using App.DataAccess.Model
@model Author
@{
    Layout = "_Page";

    ViewData["Title"] = "Author Edit Page";
    ViewData["Subtitle"] = $"This is an Author of {ViewBag.Author.Name} Modification Page";

    var author = ViewBag.Author;
}

<div class="container">
    <div class="row">
        <div class="col">
            <form asp-controller="Author" asp-action="Update" asp-route-id="@author.Id"
                method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input type="text" asp-for="Name" class="form-control" placeholder="Author Name"
                        aria-describedby="Author Name" value="@author.Name">
                    <small class="text-muted">Please input an Author Name</small>
                </div>
                <div class="form-group d-flex">
                    <a class="btn btn-primary text-white mr-2" asp-controller="Author" asp-action="Index">Author
                        List</a>
                    <button type="submit" class="btn btn-warning text-white mr-2">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

LearnASPNetCore31/App.Web/Views/Author/Index.cshtml
@using App.DataAccess.Model
@{
    Layout = "_Page";

    ViewData["Title"] = "Author Page";
    ViewData["Subtitle"] = "This is an Author List Page";
}

<div class="container">
    <div class="row mb-4">
        <div class="col d-flex justify-content-end">
            <a asp-controller="Author" asp-action="Create" class="btn btn-primary">Add Author</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Author author in ViewBag.Authors)
                    {
                        <tr>
                            <td>@author.Id</td>
                            <td>@author.Name</td>
                            <td class="d-flex">
                                <a class="btn btn-primary text-white mr-2" asp-controller="Author" asp-action="Show"
                                asp-route-id="@author.Id">Details</a>
                                <a class="btn btn-warning text-white mr-2" asp-controller="Author" asp-action="Edit"
                                asp-route-id="@author.Id">Edit</a>
                                <form asp-controller="Author" asp-action="Destroy" asp-route-id="@author.Id" method="post">
                                    <button type="submit" class="btn btn-danger text-white">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

LearnASPNetCore31/App.Web/Views/Author/Show.cshtml
@using App.DataAccess.Model
@{
    Layout = "_Page";

    ViewData["Title"] = "Author Page";
    ViewData["Subtitle"] = $"This is an Author of {ViewBag.Author.Name} Details";

    var author = ViewBag.Author;
}

<div class="container">
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Field</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>@author.Name</td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td class="d-flex justify-content-end"> <a class="btn btn-primary text-white mr-2"
                                asp-controller="Author" asp-action="Index">Author List</a>
                            <a class="btn btn-warning text-white mr-2" asp-controller="Author" asp-action="Edit"
                                asp-route-id="@author.Id">Edit</a>
                            <form asp-controller="Author" asp-action="Destroy" asp-route-id="@author.Id" method="post">
                                <button type="submit" class="btn btn-danger text-white">Delete</button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>