LearnASPNetCore31/App.Web/Controllers/Api/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

using App.DataAccess;
using App.DataAccess.Model;
using App.Web.Services;
using App.Web.Cache;

using Newtonsoft.Json;

namespace App.Web.Controllers.Api
{
    // [ApiController()]
    [Route("api/[controller]")]
    public class AuthorController : ControllerBase
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;
        // private readonly IMemoryCache _memoryCache;
        private readonly IMemoryCacheManager _memoryCacheManager;
        private readonly IContentCacheManager _contentCacheManager;

        public AuthorController(ApplicationDbContext db, IAuthorService authorService, IMemoryCacheManager memoryCacheManager, IContentCacheManager contentCacheManager)
        {
            _db = db;
            _authorService = authorService;
            _memoryCacheManager = memoryCacheManager;
            _contentCacheManager = contentCacheManager;
        }

        [HttpGet("get-all-cache-memory")]
        public async Task<IActionResult> GetAllCache()
        {
            string cacheKey = "GetAllAuthors";
            List<Author> authors;

            if (!_memoryCacheManager.TryGetCache<List<Author>>(cacheKey, out authors))
            {
                Thread.Sleep(10 * 1000);

                authors = await _authorService.GetAll(_db);
                _memoryCacheManager.SetCache<List<Author>>(cacheKey, authors);
            }

            return Ok(new
            {
                status = "success",
                message = "Authors Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = authors
                }
            });
        }

        [HttpGet("get-all-cache-content")]
        public async Task<IActionResult> GetAllCacheContent()
        {
            string cacheFilename = "GetAllAuthors.json";
            string authorsJson;
            List<Author> authors;

            if (!_contentCacheManager.TryGetCacheAsText(cacheFilename, out authorsJson))
            {
                Thread.Sleep(10 * 1000);

                authors = await _authorService.GetAll(_db);
                authorsJson = JsonConvert.SerializeObject(authors);

                _contentCacheManager.SetCacheAsText(cacheFilename, authorsJson);
            }
            else
            {
                try
                {
                    authors = JsonConvert.DeserializeObject<List<Author>>(authorsJson);
                }
                catch (JsonReaderException)
                {
                    Thread.Sleep(10 * 1000);

                    authors = await _authorService.GetAll(_db);
                    authorsJson = JsonConvert.SerializeObject(authors);

                    _contentCacheManager.SetCacheAsText(cacheFilename, authorsJson);
                }
            }

            return Ok(new
            {
                status = "success",
                message = "Authors Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = authors
                }
            });
        }

        [HttpGet("")]
        public async Task<IActionResult> GetAll()
        {
            var authors = await _authorService.GetAll(_db);

            return Ok(new
            {
                status = "success",
                message = "Authors Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = authors
                }
            });
        }

        [HttpPost("")]
        public async Task<IActionResult> Create([FromBody] Author author)
        {
            if (!ModelState.IsValid) return BadRequest(new
            {
                status = "fail",
                message = "Author Validation Invalid.",
                response = new
                {
                    errors = ModelState,
                    data = new { }
                }
            });

            await _authorService.Create(_db, author);

            return CreatedAtAction(nameof(Get), new { id = author.Id }, new
            {
                status = "success",
                message = "Author Created.",
                response = new
                {
                    errors = new object[] { },
                    data = author
                }
            });
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Get(int id)
        {
            var author = await _authorService.GetById(_db, id);

            if (author == null) return NotFound(new
            {
                status = "fail",
                message = $"Author with id: {id} not found.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });

            return Ok(new
            {
                status = "success",
                message = $"Author Retrieved Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = author
                }
            });
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] Author author)
        {
            Author existingAuthor = await _authorService.GetById(_db, id);

            if (existingAuthor == null) return NotFound(new
            {
                status = "fail",
                message = $"Author with id: {id} not found.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });

            if (!ModelState.IsValid) return BadRequest(new
            {
                status = "fail",
                message = "Author Validation Invalid.",
                response = new
                {
                    errors = ModelState,
                    data = new { }
                }
            });

            await _authorService.UpdateById(_db, id, author);

            return Ok(new
            {
                status = "success",
                message = "Author Updated Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = existingAuthor
                }
            });
        }


        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await _authorService.GetById(_db, id);

            if (author == null) return NotFound(new
            {
                status = "fail",
                message = $"Author with id: {id} not found.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });

            await _authorService.DeleteById(_db, id);

            return Ok(new
            {
                status = "success",
                message = $"Author Deleted Successfully.",
                response = new
                {
                    errors = new object[] { },
                    data = new { }
                }
            });
        }
    }
}

LearnASPNetCore31/App.Web/Controllers/Web/AuthorController.cs
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using App.DataAccess;
using App.DataAccess.Model;

using App.Web.Services;

namespace App.Web.Controllers.Web
{
    [Route("web/[controller]")]
    public class AuthorController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public AuthorController(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        [Route("index")]
        [Route("")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var authors = await _authorService.GetAll(_db);

            ViewBag.Authors = authors;

            return View();
        }

        [Route("{id}/details")]
        [Route("{id}")]
        [HttpGet]
        public async Task<IActionResult> Show(int id)
        {
            var author = await _authorService.GetById(_db, id);

            ViewBag.Author = author;

            return View();
        }

        [Route("{id}/edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var author = await _authorService.GetById(_db, id);

            ViewBag.Author = author;

            return View();
        }

        [Route("{id}/edit")]
        [HttpPost]
        public async Task<IActionResult> Update(int id, Author author)
        {
            await _authorService.UpdateById(_db, id, author);

            return RedirectToAction("Show", new { id = id });
        }

        [Route("{id}/destroy")]
        [HttpPost]
        public async Task<IActionResult> Destroy(int id)
        {
            await _authorService.DeleteById(_db, id);

            return RedirectToAction("Index");
        }

        [Route("create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("create")]
        [HttpPost]
        public async Task<IActionResult> Create(Author author)
        {
            await _authorService.Create(_db, author);

            return RedirectToAction("Index");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Create.cshtml.cs
using App.DataAccess;
using App.DataAccess.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public CreateModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        [BindProperty]
        public AuthorEntity Author { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();

            await _authorService.Create(_db, Author);

            return Redirect($"/Author/Show?id={Author.Id}");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Edit.cshtml.cs
using App.DataAccess;
using App.DataAccess.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public EditModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        [BindProperty]
        public AuthorEntity Author { get; set; }
        public int AuthorId { get; set; }

        /*
            id: AuthorId
        */
        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null) return Unauthorized();

            Author = await _authorService.GetById(_db, id);

            if (Author == null) return NotFound();

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();

            if (Author == null) return Unauthorized();

            AuthorEntity ExistingAuthor = await _authorService.GetById(_db, Author.Id);

            if (ExistingAuthor == null) return NotFound();

            await _authorService.UpdateById(_db, Author.Id, Author);

            return Redirect($"/Author/Show?id={Author.Id}");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Index.cshtml.cs
using System.Collections.Generic;
using App.DataAccess;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public IndexModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        public List<AuthorEntity> Authors { get; set; }

        public async Task OnGet()
        {
            Authors = await _authorService.GetAll(_db);
        }

        /*
            id: AuthorId
        */
        public async Task<IActionResult> OnPostDelete(int id)
        {
            AuthorEntity existingAuthor = await _authorService.GetById(_db, id);
            if (existingAuthor == null) return NotFound();

            await _authorService.DeleteById(_db, id);

            return Redirect("/Author");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Show.cshtml.cs
using System.Collections.Generic;
using App.DataAccess;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using App.Web.Services;

using AuthorEntity = App.DataAccess.Model.Author;

namespace App.Web.Pages.Author
{
    public class ShowModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorService _authorService;

        public ShowModel(ApplicationDbContext db, IAuthorService authorService)
        {
            _db = db;
            _authorService = authorService;
        }

        public AuthorEntity Author { get; set; }
        public int AuthorId { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return Unauthorized();
            }

            AuthorId = (int)id;

            Author = await _authorService.GetById(_db, AuthorId);

            if (Author == null) return NotFound();

            return Page();
        }

        /*
            id: AuthorId
        */
        public async Task<IActionResult> OnPostDelete(int id)
        {
            AuthorEntity existingAuthor = await _authorService.GetById(_db, id);
            if (existingAuthor == null) return NotFound();

            await _authorService.DeleteById(_db, id);

            return Redirect("/Author");
        }
    }
}

LearnASPNetCore31/App.Web/Pages/Author/Create.cshtml
@page
@model App.Web.Pages.Author.CreateModel
@{
    ViewData["Title"] = "Create New Author";
}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>@ViewData["Title"]</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="form-group">
                    <label asp-for="Author.Name">Name</label>
                    <input asp-for="Author.Name" type="text" class="form-control" />
                    <span asp-validation-for="Author.Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>

LearnASPNetCore31/App.Web/Pages/Author/Edit.cshtml
@page "{id:int?}"
@model App.Web.Pages.Author.EditModel
@{
    ViewData["Title"] = $"Edit Author{ " - " + Model.Author.Name}";
}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>@ViewData["Title"]</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post">
                <div asp-validation-summary="ModelOnly"></div>
                <input type="hidden" asp-for="Author.Id" />
                <div class="form-group">
                    <label asp-for="Author.Name">Name</label>
                    <input asp-for="Author.Name" type="text" class="form-control" />
                    <span asp-validation-for="Author.Name" class="text-danger"></span>
                </div>
                <a asp-area="" asp-page="/Author/Index" class="btn btn-danger">Back</a>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>

LearnASPNetCore31/App.Web/Pages/Author/Index.cshtml
@page
@model App.Web.Pages.Author.IndexModel
@using AuthorEntity = App.DataAccess.Model.Author
@{
    ViewData["Title"] = "List of Authors";
}

<div class="container">
    <div class="row mb-2">
        <div class="col-9">
            @ViewData["Title"]
        </div>
        <div class="col-3 d-flex justify-content-end">
            <a class="btn btn-primary" asp-area="" asp-page="/Author/Create">Create Author</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @{
                var authors = Model.Authors;
                if (authors.Count > 0)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (AuthorEntity author in authors)
                            {
                                <tr>
                                    <td class="col-2">@author.Id</td>
                                    <td class="col-8">@author.Name</td>
                                    <td class="col-2 d-flex">
                                        <a class="btn btn-info mr-2" asp-area="" asp-page="/Author/Show"
                                asp-route-id="@author.Id">Details</a>
                                        <a class="btn btn-warning mr-2" asp-area="" asp-page="/Author/Edit"
                                asp-route-id="@author.Id">Edit</a>
                                        <form class="d-inline-block" asp-page-handler="Delete" asp-route-id="@author.Id"
                                method="post">
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p class="fs-4">No Author Data Currently.</p>
                }
            }
        </div>
    </div>
</div>

LearnASPNetCore31/App.Web/Pages/Author/Show.cshtml
@page "{id:int?}"
@model App.Web.Pages.Author.ShowModel
@using AuthorEntity = App.DataAccess.Model.Author
@{
    ViewData["Title"] = "Author Information";
}

<div class="container">
    <div class="row mb-2">
        <div class="col-9">
            @ViewData["Title"]
        </div>
        <div class="col-3 d-flex justify-content-end">
            <a class="btn btn-danger" asp-area="" asp-page="/Author/Index">Author List</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @{
                AuthorEntity author = Model.Author;
                if (author == null)
                {
                    <p class="fs-4">Author Information Not Found.</p>
                }
                else
                {
                    <div>
                        <div class="form-group row">
                            <label>Id</label>
                            <span type="text" class="form-control">@author.Id</span>
                        </div>
                        <div class="form-group row">
                            <label>Name</label>
                            <span type="text" class="form-control">@author.Name</span>
                        </div>
                        <form class="d-inline-block" asp-page-handler="Delete" asp-route-id="@author.Id" method="post">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                }
            }
        </div>
    </div>
</div>